import turtle
turtle.bgcolor("black")
t = turtle.Pen()
t.pencolor("red")
t.forward(100)
t.pencolor("orange")
t.forward(100)
t.pencolor("yellow")
t.forward(100)

t.right(90)

t.pencolor("blue")
t.forward(94)
t.pencolor("indigo")
t.forward(94)
t.pencolor("violet")
t.forward(94)

t.right(90)
t.pencolor("red")
t.forward(102)
t.pencolor("orange")
t.forward(102)
t.pencolor("yellow")
t.forward(102)
t.pencolor("blue")
t.forward(102)
t.pencolor("indigo")
t.forward(102)
t.pencolor("violet")
t.forward(102)
t.right(90)
t.pencolor("red")
t.forward(96)
t.pencolor("orange")
t.forward(96)
t.pencolor("yellow")
t.forward(96)
t.pencolor("blue")
t.forward(96)
t.pencolor("indigo")
t.forward(96)
t.pencolor("violet")
t.forward(96)
t.right(90)
t.pencolor("red")
t.forward(102)
t.pencolor("orange")
t.forward(102)
t.pencolor("yellow")
t.forward(102)
t.pencolor("blue")
t.forward(102)
t.pencolor("indigo")
t.forward(102)
t.pencolor("violet")
t.forward(102)
t.right(90)
t.pencolor("red")
t.forward(100)
t.pencolor("orange")
t.forward(100)
t.pencolor("yellow")
t.forward(100)


